#!/usr/bin/env python3
"""Generate a slimmed Strings facade + StringsA-E for the shell template.

The shell runtime only needs a subset of the host i18n surface (~one third of
the members). This script scans the *already synced* shell runtime sources for
`Strings.x` / `StringsX.y` references, expands the closure over member bodies
(e.g. a facade delegate `val x get() = StringsA.x` pulls in `StringsA.x`), and
emits reduced copies of `Strings.kt` and `StringsA.kt`..`StringsE.kt` that carry
only the referenced members — verbatim, so translations stay identical.

Failure model: member bodies are copied byte-for-byte; an unresolved reference
shows up as a shell compile error, not a silent behaviour change. Over-matching
in the reference scan is harmless (worst case a few extra strings ship).

Usage:
  generate_shell_strings.py --synced-src <dir> --app-i18n <dir> --out <dir>
"""

import argparse
import re
import sys
from pathlib import Path

OUT_PACKAGE_DIR = "com/webtoapp/core/i18n"

GENERATED_HEADER = (
    "// Generated by scripts/generate_shell_strings.py — shell runtime strings only.\n"
    "// Do not edit; the canonical sources live in app/src/main/java/com/webtoapp/core/i18n/.\n"
)

DECL_RE = re.compile(
    r"\b(val|var|fun)\s+(?:<[^>]+>\s*)?(?:[\w.\[\]?]+\s*\.\s*)?([A-Za-z_]\w*)"
)
DELEGATE_RE = re.compile(r"=\s*Strings[A-E]\s*\.")
# Word-boundary lookbehind: `JsStrings.quote` must not register `Strings.quote`.
FACADE_REF_RE = re.compile(r"(?<![A-Za-z0-9_])Strings\s*\.\s*([A-Za-z_]\w*)")
SPLIT_REF_RE = re.compile(r"(?<![A-Za-z0-9_])Strings([A-E])\s*\.\s*([A-Za-z_]\w*)")
CONTINUATION_CHARS = set("+-*/%|&,.?:")


def mask_code(text: str) -> str:
    """Blank out comments and string/char literal contents, preserving length.

    String templates (${...}) stay masked too — code braces inside a literal are
    not member delimiters, so hiding them keeps brace tracking simple and right.
    """
    mask = list(text)
    n = len(text)
    i = 0
    state = "code"  # code | line_comment | block_comment | string | triple | char
    block_depth = 0
    while i < n:
        c = text[i]
        if state == "code":
            if c == "/" and i + 1 < n and text[i + 1] == "/":
                state = "line_comment"
                mask[i] = mask[i + 1] = " "
                i += 2
                continue
            if c == "/" and i + 1 < n and text[i + 1] == "*":
                state = "block_comment"
                block_depth = 1
                mask[i] = mask[i + 1] = " "
                i += 2
                continue
            if text.startswith('"""', i):
                state = "triple"
                mask[i] = mask[i + 1] = mask[i + 2] = " "
                i += 3
                continue
            if c == '"':
                state = "string"
                mask[i] = " "
                i += 1
                continue
            if c == "'":
                state = "char"
                mask[i] = " "
                i += 1
                continue
            i += 1
        elif state == "line_comment":
            mask[i] = "\n" if c == "\n" else " "
            if c == "\n":
                state = "code"
            i += 1
        elif state == "block_comment":
            if text.startswith("/*", i):
                block_depth += 1
                mask[i] = mask[i + 1] = " "
                i += 2
                continue
            if text.startswith("*/", i):
                block_depth -= 1
                mask[i] = mask[i + 1] = " "
                i += 2
                if block_depth == 0:
                    state = "code"
                continue
            if c != "\n":
                mask[i] = " "
            i += 1
        elif state == "string":
            if c == "\\":
                mask[i] = " "
                if i + 1 < n:
                    mask[i + 1] = " "
                i += 2
                continue
            mask[i] = "\n" if c == "\n" else " "
            if c == '"':
                state = "code"
            i += 1
        elif state == "triple":
            if text.startswith('"""', i):
                mask[i] = mask[i + 1] = mask[i + 2] = " "
                i += 3
                state = "code"
                continue
            if c != "\n":
                mask[i] = " "
            i += 1
        elif state == "char":
            if c == "\\":
                mask[i] = " "
                if i + 1 < n:
                    mask[i + 1] = " "
                i += 2
                continue
            mask[i] = "\n" if c == "\n" else " "
            if c == "'":
                state = "code"
            i += 1
    return "".join(mask)


class Member:
    __slots__ = ("name", "kind", "start", "end", "text")

    def __init__(self, name, kind, start, end, text):
        self.name = name
        self.kind = kind
        self.start = start
        self.end = end
        self.text = text


def _is_eq(mask_line: str, j: int) -> bool:
    """True when mask_line[j] is '=' that is not part of ==, <=, >=, !=, ===."""
    prev = mask_line[j - 1] if j > 0 else " "
    nxt = mask_line[j + 1] if j + 1 < len(mask_line) else " "
    return nxt != "=" and prev not in "<>!="


def _expr_complete(mask_lines, start_i, col):
    """Scan from (start_i, col) — positioned just after '=' / 'by'.

    Returns index of the line on which the expression completes. Brackets of
    every kind must balance; a trailing continuation operator keeps it going.
    """
    depth = {"(": 0, "{": 0, "[": 0}
    pairs = {")": "(", "}": "{", "]": "["}
    i = start_i
    while i < len(mask_lines):
        line = mask_lines[i]
        seg = line[col:] if i == start_i else line
        for ch in seg:
            if ch in depth:
                depth[ch] += 1
            elif ch in pairs:
                depth[pairs[ch]] -= 1
        if depth["("] <= 0 and depth["{"] <= 0 and depth["["] <= 0:
            stripped = seg.rstrip()
            if stripped and stripped[-1] in CONTINUATION_CHARS:
                i += 1
                col = 0
                continue
            return i
        i += 1
        col = 0
    return len(mask_lines) - 1


def _block_end(mask_lines, start_i, col):
    """Scan from (start_i, col) at the first '{' — return the line closing it."""
    depth = 0
    i = start_i
    while i < len(mask_lines):
        line = mask_lines[i]
        seg = line[col:] if i == start_i else line
        for ch in seg:
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth <= 0:
                    return i
        i += 1
        col = 0
    return len(mask_lines) - 1


def _accessor_start(mask_line: str) -> bool:
    return bool(re.match(r"^\s*(get|set)\b", mask_line))


def _next_code_line(mask_lines, i):
    nxt = i + 1
    while nxt < len(mask_lines) and not mask_lines[nxt].strip():
        nxt += 1
    return nxt


def _find_member_end(mask_lines, start_i, kw_col):
    """Locate the end line of a member whose keyword sits at (start_i, kw_col)."""
    paren = 0
    i = start_i
    col = kw_col
    while i < len(mask_lines):
        line = mask_lines[i]
        base = col if i == start_i else 0
        seg = line[base:]
        j = 0
        while j < len(seg):
            ch = seg[j]
            if ch == "(":
                paren += 1
            elif ch == ")":
                paren -= 1
            elif paren <= 0:
                if ch == "{":
                    return _block_end(mask_lines, i, base + j)
                if ch == "=" and _is_eq(line, base + j):
                    return _expr_complete(mask_lines, i, base + j + 1)
                if (
                    ch == "b"
                    and seg.startswith("by", j)
                    and (j + 2 >= len(seg) or not seg[j + 2].isalnum())
                    and (j == 0 or not seg[j - 1].isalnum())
                ):
                    return _expr_complete(mask_lines, i, base + j + 2)
            j += 1
        # No '=' / '{' on this line: the declaration continues only via
        # accessors (get/set blocks). Consume accessor blocks while they follow.
        nxt = _next_code_line(mask_lines, i)
        if nxt < len(mask_lines) and _accessor_start(mask_lines[nxt]):
            acc_col = mask_lines[nxt].index(mask_lines[nxt].strip()[0])
            i = nxt
            col = acc_col
            # The accessor line itself gets scanned by the same loop above.
            end = _scan_accessor(mask_lines, i, col)
            # Possibly a second accessor (get + set).
            probe = _next_code_line(mask_lines, end)
            if probe < len(mask_lines) and _accessor_start(mask_lines[probe]):
                acc_col2 = mask_lines[probe].index(mask_lines[probe].strip()[0])
                return _scan_accessor(mask_lines, probe, acc_col2)
            return end
        return i


def _scan_accessor(mask_lines, i, col):
    """End line for one accessor starting at (i, col): `get() {` or `get() = e`."""
    line = mask_lines[i]
    seg = line[col:]
    j = 0
    paren = 0
    while j < len(seg):
        ch = seg[j]
        if ch == "(":
            paren += 1
        elif ch == ")":
            paren -= 1
        elif paren <= 0:
            if ch == "{":
                return _block_end(mask_lines, i, col + j)
            if ch == "=" and _is_eq(line, col + j):
                return _expr_complete(mask_lines, i, col + j + 1)
        j += 1
    return i


def parse_members(path: Path):
    """Split a Strings file into header, object members, and top-level members."""
    text = path.read_text(encoding="utf-8")
    mask = mask_code(text)
    lines = text.splitlines(keepends=True)
    mask_lines = mask.splitlines(keepends=True)

    obj_m = re.search(r"\bobject\s+([A-Za-z_]\w*)\s*\{", mask)
    if not obj_m:
        raise SystemExit(f"{path}: no `object X {{` found")
    obj_line = mask[: obj_m.start()].count("\n")
    line_start = mask.rfind("\n", 0, obj_m.end()) + 1
    brace_col = obj_m.end() - 1 - line_start
    obj_body_end_line = _block_end(mask_lines, obj_line, brace_col)

    depth_at_line = []
    depth = 0
    for ml in mask_lines:
        depth_at_line.append(depth)
        for ch in ml:
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1

    members = []
    toplevel = []
    i = 0
    n = len(lines)
    while i < n:
        in_obj = obj_line < i < obj_body_end_line and depth_at_line[i] == 1
        in_top = i > obj_body_end_line and depth_at_line[i] == 0
        if in_obj or in_top:
            m = DECL_RE.search(mask_lines[i])
            if m:
                kind, name = m.group(1), m.group(2)
                kw_col = m.start(1)
                start = i
                while start - 1 >= 0 and re.match(r"^\s*@", mask_lines[start - 1]):
                    start -= 1
                end = _find_member_end(mask_lines, i, kw_col)
                (members if in_obj else toplevel).append((name, kind, start, end))
                i = end + 1
                continue
        i += 1

    header = "".join(lines[: obj_line + 1])
    member_objs = [
        Member(name, kind, s, e, "".join(lines[s : e + 1]))
        for name, kind, s, e in members
    ]
    toplevel_objs = [
        Member(name, kind, s, e, "".join(lines[s : e + 1]))
        for name, kind, s, e in toplevel
    ]
    return header, member_objs, toplevel_objs


ALIAS_IMPORT_RE = re.compile(
    r"import\s+com\.webtoapp\.core\.i18n\.Strings([A-E]?)\s+as\s+([A-Za-z_]\w*)"
)
ALIAS_VAL_RE = re.compile(
    r"\b(?:val|var)\s+([A-Za-z_]\w*)\s*=\s*(?:com\.webtoapp\.core\.i18n\.)?Strings([A-E]?)\b"
)


def collect_seeds(roots):
    """Returns (facade, split, alias_facade, alias_split, blob).

    Direct `Strings.x` refs are hard requirements (fail loud if unresolvable).
    Alias refs (`S.x` for `val S = Strings`) are soft: the alias may collide
    with an unrelated same-named variable in the file, so names that don't
    resolve to real members are dropped instead of erroring.
    """
    facade = set()
    split = {letter: set() for letter in "ABCDE"}
    alias_facade = set()
    alias_split = {letter: set() for letter in "ABCDE"}
    blob_parts = []
    kt_files = sorted(
        f for root in roots for f in root.rglob("*.kt") if f.is_file()
    )
    for kt in kt_files:
        src = kt.read_text(encoding="utf-8", errors="replace")
        blob_parts.append(src)
        facade.update(FACADE_REF_RE.findall(src))
        for letter, name in SPLIT_REF_RE.findall(src):
            split[letter].add(name)
        aliases = {}
        for letter, alias in ALIAS_IMPORT_RE.findall(src):
            aliases[alias] = letter
        for alias, letter in ALIAS_VAL_RE.findall(src):
            aliases.setdefault(alias, letter)
        for alias, letter in aliases.items():
            ref_re = re.compile(
                rf"(?<![A-Za-z0-9_]){re.escape(alias)}\s*\.\s*([A-Za-z_]\w*)"
            )
            for name in ref_re.findall(src):
                if letter:
                    alias_split[letter].add(name)
                else:
                    alias_facade.add(name)
    return facade, split, alias_facade, alias_split, "\n".join(blob_parts)


def _index(members):
    by_name = {}
    for m in members:
        by_name.setdefault(m.name, []).append(m)
    return by_name


def expand_closure(facade_members, split_members, needed_facade, needed_split):
    """Pull in members referenced from already-needed member bodies."""
    by_name_f = _index(facade_members)
    by_name_s = {letter: _index(members) for letter, members in split_members.items()}

    def total():
        return len(needed_facade) + sum(len(s) for s in needed_split.values())

    def scan(text):
        for letter, name in SPLIT_REF_RE.findall(text):
            needed_split[letter].add(name)
        for name in FACADE_REF_RE.findall(text):
            needed_facade.add(name)

    prev = -1
    while total() != prev:
        prev = total()
        for name in list(needed_facade):
            for m in by_name_f.get(name, []):
                scan(m.text)
        for letter in "ABCDE":
            for name in list(needed_split[letter]):
                for m in by_name_s[letter].get(name, []):
                    scan(m.text)


def emit_file(header, members, needed_names, out_path, extra=""):
    parts = [GENERATED_HEADER, header]
    for m in members:
        if m.name in needed_names:
            parts.append("\n" + m.text.rstrip("\n") + "\n")
    parts.append("}\n")
    if extra:
        parts.append(extra)
    out_path.write_text("".join(parts), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--synced-src", required=True, type=Path)
    ap.add_argument(
        "--also-scan",
        type=Path,
        default=[],
        nargs="*",
        help="extra source roots compiled into the shell (e.g. java-overrides)",
    )
    ap.add_argument("--app-i18n", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    scan_roots = [args.synced_src, *args.also_scan]
    for root in scan_roots:
        if not root.exists():
            raise SystemExit(f"scan root missing: {root}")

    needed_facade, needed_split, alias_facade, alias_split, blob = collect_seeds(
        scan_roots
    )

    header_f, facade_members, toplevel = parse_members(args.app_i18n / "Strings.kt")
    split_data = {}
    for letter in "ABCDE":
        h, members, tl = parse_members(args.app_i18n / f"Strings{letter}.kt")
        if tl:
            names = [m.name for m in tl]
            raise SystemExit(f"Strings{letter}.kt: unexpected top-level members: {names}")
        split_data[letter] = (h, members)
    split_members = {letter: members for letter, (_, members) in split_data.items()}

    # Soft alias refs: keep only names that really exist (collisions with an
    # unrelated same-named variable are expected and simply dropped).
    facade_names = {m.name for m in facade_members}
    needed_facade |= alias_facade & facade_names
    for letter in "ABCDE":
        names = {m.name for m in split_members[letter]}
        needed_split[letter] |= alias_split[letter] & names

    # Members before the first pure delegate are infrastructure (language state,
    # init helpers) — always emitted so `Strings.lang` & friends keep working.
    # Added BEFORE the closure pass: a same-named delegate member (e.g. the
    # `attachContext` string vs `attachContext()` fun) gets emitted alongside,
    # and the closure must then resolve *its* delegate target too.
    for m in facade_members:
        if DELEGATE_RE.search(m.text):
            break
        needed_facade.add(m.name)

    # Top-level members (InitializeLanguage): emit only when referenced; their
    # bodies feed the same reference closure.
    needed_toplevel = [
        m for m in toplevel if re.search(rf"\b{re.escape(m.name)}\b", blob)
    ]
    for m in needed_toplevel:
        for letter, name in SPLIT_REF_RE.findall(m.text):
            needed_split[letter].add(name)
        for name in FACADE_REF_RE.findall(m.text):
            needed_facade.add(name)

    expand_closure(facade_members, split_members, needed_facade, needed_split)

    # Fail loud on anything the parser could not resolve.
    missing = needed_facade - facade_names
    if missing:
        raise SystemExit(
            f"Unresolved Strings.* members referenced by shell code: {sorted(missing)}"
        )
    for letter in "ABCDE":
        names = {m.name for m in split_members[letter]}
        missing_s = needed_split[letter] - names
        if missing_s:
            raise SystemExit(f"Unresolved Strings{letter}.* members: {sorted(missing_s)}")

    out_dir = args.out / OUT_PACKAGE_DIR
    out_dir.mkdir(parents=True, exist_ok=True)

    extra = "".join("\n" + m.text.rstrip("\n") + "\n" for m in needed_toplevel)
    emit_file(header_f, facade_members, needed_facade, out_dir / "Strings.kt", extra)
    for letter in "ABCDE":
        h, members = split_data[letter]
        emit_file(h, members, needed_split[letter], out_dir / f"Strings{letter}.kt")

    total_in = sum(
        (args.app_i18n / f).stat().st_size for f in ["Strings.kt"] + [f"Strings{c}.kt" for c in "ABCDE"]
    )
    total_out = sum(
        (out_dir / f).stat().st_size for f in ["Strings.kt"] + [f"Strings{c}.kt" for c in "ABCDE"]
    )
    print(
        "generateShellStrings: facade %d/%d members, splits %d/%d members, "
        "toplevel %s; %.0f KB -> %.0f KB source"
        % (
            len(needed_facade),
            len({m.name for m in facade_members}),
            sum(len(s) for s in needed_split.values()),
            sum(len({m.name for m in ms}) for ms in split_members.values()),
            [m.name for m in needed_toplevel],
            total_in / 1024,
            total_out / 1024,
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
